<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerGx2YOkN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGx2YOkN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGx2YOkN.legacy');
=======
if (\class_exists(\ContainerKwrDFA1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwrDFA1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKwrDFA1.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerGx2YOkN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGx2YOkN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gx2YOkN',
    'container.build_id' => '3b23a273',
    'container.build_time' => 1715252909,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGx2YOkN');
=======
    \class_alias(\ContainerKwrDFA1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKwrDFA1\App_KernelDevDebugContainer([
    'container.build_hash' => 'KwrDFA1',
    'container.build_id' => '003ed542',
    'container.build_time' => 1715709136,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwrDFA1');
>>>>>>> Stashed changes
