<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXC6rNCj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXC6rNCj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXC6rNCj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXC6rNCj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXC6rNCj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XC6rNCj',
    'container.build_id' => '5e3ebcf4',
    'container.build_time' => 1715797733,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXC6rNCj');
