<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerGx2YOkN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGx2YOkN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGx2YOkN.legacy');
=======
if (\class_exists(\ContainerPYNm3tb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYNm3tb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYNm3tb.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerGx2YOkN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGx2YOkN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gx2YOkN',
    'container.build_id' => '3b23a273',
    'container.build_time' => 1715252909,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGx2YOkN');
=======
    \class_alias(\ContainerPYNm3tb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYNm3tb\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYNm3tb',
    'container.build_id' => 'b7a41848',
    'container.build_time' => 1715732992,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYNm3tb');
>>>>>>> Stashed changes
