<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
<<<<<<< Updated upstream
=======
    'app_anadir_nuevo_libro' => [[], ['_controller' => 'App\\Controller\\AnadirNuevoLibroController::nuevo'], [], [['text', '/anadir/nuevo/libro']], [], [], []],
    'app_buscar_bilioteca_ciudad' => [[], ['_controller' => 'App\\Controller\\BuscarBiliotecaCiudadController::index'], [], [['text', '/buscar/bilioteca/ciudad']], [], [], []],
    'app_buscar_bilioteca_nombre' => [[], ['_controller' => 'App\\Controller\\BuscarBiliotecaNombreController::index'], [], [['text', '/buscar/bilioteca/nombre']], [], [], []],
    'app_buscar_libro_autor_bilioteca' => [[], ['_controller' => 'App\\Controller\\BuscarLibroAutorBiliotecaController::index'], [], [['text', '/buscar/libro/autor/bilioteca']], [], [], []],
    'app_buscar_libro_editorial_bilioteca' => [[], ['_controller' => 'App\\Controller\\BuscarLibroEditorialBiliotecaController::index'], [], [['text', '/buscar/libro/editorial/bilioteca']], [], [], []],
    'app_buscar_libro_titulo_bilioteca' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloBiliotecaController::index'], [], [['text', '/buscar/libro/titulo/bilioteca']], [], [], []],
    'app_buscar_libro_titulo' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloController::index'], [], [['text', '/buscar/libro/titulo']], [], [], []],
    'app_buscar_libro_titulo_disponibilidad' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloDisponibilidadController::index'], [], [['text', '/buscar/libro/titulo/disponibilidad']], [], [], []],
    'app_listar_bibliotecas' => [[], ['_controller' => 'App\\Controller\\ListarBibliotecasController::index'], [], [['text', '/listar/bibliotecas']], [], [], []],
    'app_listar_libros_bilioteca' => [[], ['_controller' => 'App\\Controller\\ListarLibrosBiliotecaController::index'], [], [['text', '/listar/libros/bilioteca']], [], [], []],
    'App\Controller\AnadirNuevoLibroController::nuevo' => [[], ['_controller' => 'App\\Controller\\AnadirNuevoLibroController::nuevo'], [], [['text', '/anadir/nuevo/libro']], [], [], []],
    'App\Controller\BuscarBiliotecaCiudadController::index' => [[], ['_controller' => 'App\\Controller\\BuscarBiliotecaCiudadController::index'], [], [['text', '/buscar/bilioteca/ciudad']], [], [], []],
    'App\Controller\BuscarBiliotecaNombreController::index' => [[], ['_controller' => 'App\\Controller\\BuscarBiliotecaNombreController::index'], [], [['text', '/buscar/bilioteca/nombre']], [], [], []],
    'App\Controller\BuscarLibroAutorBiliotecaController::index' => [[], ['_controller' => 'App\\Controller\\BuscarLibroAutorBiliotecaController::index'], [], [['text', '/buscar/libro/autor/bilioteca']], [], [], []],
    'App\Controller\BuscarLibroEditorialBiliotecaController::index' => [[], ['_controller' => 'App\\Controller\\BuscarLibroEditorialBiliotecaController::index'], [], [['text', '/buscar/libro/editorial/bilioteca']], [], [], []],
    'App\Controller\BuscarLibroTituloBiliotecaController::index' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloBiliotecaController::index'], [], [['text', '/buscar/libro/titulo/bilioteca']], [], [], []],
    'App\Controller\BuscarLibroTituloController::index' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloController::index'], [], [['text', '/buscar/libro/titulo']], [], [], []],
    'App\Controller\BuscarLibroTituloDisponibilidadController::index' => [[], ['_controller' => 'App\\Controller\\BuscarLibroTituloDisponibilidadController::index'], [], [['text', '/buscar/libro/titulo/disponibilidad']], [], [], []],
    'App\Controller\ListarBibliotecasController::index' => [[], ['_controller' => 'App\\Controller\\ListarBibliotecasController::index'], [], [['text', '/listar/bibliotecas']], [], [], []],
    'App\Controller\ListarLibrosBiliotecaController::index' => [[], ['_controller' => 'App\\Controller\\ListarLibrosBiliotecaController::index'], [], [['text', '/listar/libros/bilioteca']], [], [], []],
>>>>>>> Stashed changes
];
