<?php

namespace ContainerCKk1Tnw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KqGXT5kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kqGXT5k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kqGXT5k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'libroRepository' => ['privates', 'App\\Repository\\LibroRepository', 'getLibroRepositoryService', true],
        ], [
            'entityManager' => '?',
            'libroRepository' => 'App\\Repository\\LibroRepository',
        ]);
    }
}
