<?php

namespace ContainerAbPt4Eh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XN_UUjeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XN.uUje' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XN.uUje'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AnadirNuevoLibroController::nuevo' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EditarBibliotecaController::index' => ['privates', '.service_locator.guaRQS0', 'get_ServiceLocator_GuaRQS0Service', true],
            'App\\Controller\\EditarLibroController::index' => ['privates', '.service_locator.kqGXT5k', 'get_ServiceLocator_KqGXT5kService', true],
            'App\\Controller\\InsertarBibliotecaController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AnadirNuevoLibroController:nuevo' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EditarBibliotecaController:index' => ['privates', '.service_locator.guaRQS0', 'get_ServiceLocator_GuaRQS0Service', true],
            'App\\Controller\\EditarLibroController:index' => ['privates', '.service_locator.kqGXT5k', 'get_ServiceLocator_KqGXT5kService', true],
            'App\\Controller\\InsertarBibliotecaController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AnadirNuevoLibroController::nuevo' => '?',
            'App\\Controller\\EditarBibliotecaController::index' => '?',
            'App\\Controller\\EditarLibroController::index' => '?',
            'App\\Controller\\InsertarBibliotecaController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnadirNuevoLibroController:nuevo' => '?',
            'App\\Controller\\EditarBibliotecaController:index' => '?',
            'App\\Controller\\EditarLibroController:index' => '?',
            'App\\Controller\\InsertarBibliotecaController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
