<?php

<<<<<<<< Updated upstream:ProyectoSymfony/var/cache/dev/ContainerN3IxC6q/getListarBibliotecasControllerService.php
namespace ContainerN3IxC6q;
========
namespace ContainerARRdM49;
>>>>>>>> Stashed changes:ProyectoSymfony/var/cache/dev/ContainerARRdM49/getListarBibliotecasControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListarBibliotecasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ListarBibliotecasController' shared autowired service.
     *
     * @return \App\Controller\ListarBibliotecasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ListarBibliotecasController.php';

        $container->services['App\\Controller\\ListarBibliotecasController'] = $instance = new \App\Controller\ListarBibliotecasController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ListarBibliotecasController', $container));

        return $instance;
    }
}
