<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Biblioteca extends \App\Entity\Biblioteca implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Ciudad' => [parent::class, 'Ciudad', null],
        "\0".parent::class."\0".'Direccion' => [parent::class, 'Direccion', null],
        "\0".parent::class."\0".'FechaFundacion' => [parent::class, 'FechaFundacion', null],
        "\0".parent::class."\0".'HorarioApertura' => [parent::class, 'HorarioApertura', null],
        "\0".parent::class."\0".'HorarioCierre' => [parent::class, 'HorarioCierre', null],
        "\0".parent::class."\0".'Nombre' => [parent::class, 'Nombre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Ciudad' => [parent::class, 'Ciudad', null],
        'Direccion' => [parent::class, 'Direccion', null],
        'FechaFundacion' => [parent::class, 'FechaFundacion', null],
        'HorarioApertura' => [parent::class, 'HorarioApertura', null],
        'HorarioCierre' => [parent::class, 'HorarioCierre', null],
        'Nombre' => [parent::class, 'Nombre', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
