<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Biblioteca extends \App\Entity\Biblioteca implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ciudad' => [parent::class, 'ciudad', null],
        "\0".parent::class."\0".'direccion' => [parent::class, 'direccion', null],
        "\0".parent::class."\0".'fecha_fundacion' => [parent::class, 'fecha_fundacion', null],
        "\0".parent::class."\0".'horario_apertura' => [parent::class, 'horario_apertura', null],
        "\0".parent::class."\0".'horario_cierre' => [parent::class, 'horario_cierre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        'ciudad' => [parent::class, 'ciudad', null],
        'direccion' => [parent::class, 'direccion', null],
        'fecha_fundacion' => [parent::class, 'fecha_fundacion', null],
        'horario_apertura' => [parent::class, 'horario_apertura', null],
        'horario_cierre' => [parent::class, 'horario_cierre', null],
        'id' => [parent::class, 'id', null],
        'nombre' => [parent::class, 'nombre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
