<?php

namespace ContainerSO4lYH1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GuaRQS0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.guaRQS0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.guaRQS0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bibliotecaRepository' => ['privates', 'App\\Repository\\BibliotecaRepository', 'getBibliotecaRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'bibliotecaRepository' => 'App\\Repository\\BibliotecaRepository',
            'entityManager' => '?',
        ]);
    }
}
