<?php

<<<<<<<< Updated upstream:ProyectoSymfony/var/cache/dev/ContainerN3IxC6q/getListarLibrosBiliotecaControllerService.php
namespace ContainerN3IxC6q;
========
namespace ContainerTy2vig9;
>>>>>>>> Stashed changes:ProyectoSymfony/var/cache/dev/ContainerTy2vig9/getListarLibrosBiliotecaControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListarLibrosBiliotecaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ListarLibrosBiliotecaController' shared autowired service.
     *
     * @return \App\Controller\ListarLibrosBiliotecaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ListarLibrosBiliotecaController.php';

        $container->services['App\\Controller\\ListarLibrosBiliotecaController'] = $instance = new \App\Controller\ListarLibrosBiliotecaController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ListarLibrosBiliotecaController', $container));

        return $instance;
    }
}
